FROM node:10-alpine
ARG API_URL
ARG REDIRECT_URL_AFTER_ZOOM
ARG ZOOM_CLIENT_ID
WORKDIR /app
COPY . .
RUN yarn && yarn build
ENV NODE_ENV=production
ENV API_URL=${API_URL_ARG}
ENV REDIRECT_URL_AFTER_ZOOM=${REDIRECT_URL_AFTER_ZOOM}
ENV ZOOM_CLIENT_ID=${ZOOM_CLIENT_ID}
EXPOSE 80
CMD node server.js
