export const mocks = [
  { id: 1, title: `Don't be alone` },
  { id: 2, title: `To play guitar` },
  { id: 3, title: `Draw` },
  { id: 4, title: `Learn English` },
  { id: 5, title: `Be more productive` },
  { id: 6, title: `To meditate` },
  { id: 7, title: `Be more productive` },
  { id: 8, title: `To meditate` },
  { id: 9, title: `Learn spanish` },
  { id: 10, title: `Learn English` },
  { id: 11, title: `Public speaking` },
  { id: 12, title: `To meditate` },
  { id: 13, title: `To program` },
  { id: 14, title: `Write` },
  { id: 15, title: `To program` },
  { id: 16, title: `Write` },
  { id: 17, title: `Don't be alone` },
  { id: 18, title: `To play guitar` },
  { id: 19, title: `Draw` },
  { id: 20, title: `Learn English` },
  { id: 21, title: `Be more productive` },
  { id: 22, title: `To meditate` },
  { id: 23, title: `Be more productive` },
  { id: 24, title: `To meditate` },
  { id: 25, title: `Learn spanish` },
  { id: 26, title: `Learn English` },
  { id: 27, title: `Public speaking` },
  { id: 28, title: `To meditate` },
  { id: 29, title: `To program` },
  { id: 30, title: `Write` },
  { id: 31, title: `To program` },
  { id: 32, title: `Write` },
  { id: 532, title: `Write` },
  { id: 33, title: `Don't be alone` },
  { id: 34, title: `To play guitar` },
  { id: 35, title: `Draw` },
  { id: 36, title: `Learn English` },
  { id: 37, title: `Be more productive` },
  { id: 38, title: `To meditate` },
  { id: 39, title: `Be more productive` },
  { id: 40, title: `To meditate` },
  { id: 41, title: `Learn spanish` },
  { id: 42, title: `Learn English` },
  { id: 43, title: `Public speaking` },
  { id: 44, title: `To meditate` },
  { id: 45, title: `To program` },
  { id: 46, title: `Write` },
  { id: 47, title: `To program` },
  { id: 48, title: `Write` },
];
